# Generated by Django 2.2.5 on 2020-01-09 08:23

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='join',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=20)),
                ('yy', models.IntegerField()),
                ('mm', models.IntegerField()),
                ('dd', models.IntegerField()),
                ('gd', models.CharField(max_length=20)),
                ('em', models.TextField()),
                ('ph', models.IntegerField()),
                ('regdate', models.DateField(auto_now_add=True)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
