# Generated by Django 3.0.1 on 2020-01-12 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='join',
            new_name='table',
        ),
    ]
